#/bin/bash 

# Validation 
[ -z "$EXTERNAL_CONF_HOSTNAME_SERVICE_PROVIDER" ] && echo "Missing HOSTNAME" && exit 125
[ -z "$EXTERNAL_CONF_SHIB_AUTH_APP_IP_PORT" ] && echo "Missing EXTERNAL_CONF_SHIB_AUTH_APP_IP_PORT" && exit 125
[ -z "$EXTERNAL_CONF_DISCOVERY_SERVICE_URL" ] && echo "Missing EXTERNAL_CONF_DISCOVERY_SERVICE_URL" && exit 125
[ -z "$EXTERNAL_CONF_DISCOVERY_SERVICE_METADATA_URL" ] && echo "Missing EXTERNAL_CONF_DISCOVERY_SERVICE_METADATA_URL" && exit 125
[ -z "$EXTERNAL_CONF_SERVICE_PROVIDER_CERTIFICATE_NAME" ] && echo "Missing EXTERNAL_CONF_SERVICE_PROVIDER_CERTIFICATE_NAME" && exit 125
[ -z "$EXTERNAL_CONF_SERVICE_PROVIDER_KEY_NAME" ] && echo "Missing EXTERNAL_CONF_SERVICE_PROVIDER_KEY_NAME" && exit 125
[ -z "$EXTERNAL_CONF_SHIB_AUTH_VM_PUBLIC_KEY_NAME" ] && echo "Missing EXTERNAL_CONF_SHIB_AUTH_VM_PUBLIC_KEY_NAME" && exit 125

# -- Constants Start --
DEFAULT_NAME_TO_REPLACE_ADDRESS_SHIBBOLETH_AUTH_APPLICATION='_ADDRESS_SHIBBOLETH_AUTH_APPLICATION_'
DEFAULT_NAME_TO_REPLACE_HOSTNAME='_HOSTNAME_'
DEFAULT_NAME_TO_REPLACE_DISCOVERY_SERVICE='_DS_'
DEFAULT_NAME_TO_REPLACE_DISCOVERY_SERVICE_METADATA='_DS_META_'

DEFAULT_FILES_CONF_STATIC_PATH_INTO_CONTAINER='/root/files-conf-static'
DEFAULT_FILES_CONF_DINAMIC_PATH_INTO_CONTAINER='/root/files-conf-dinamic'

APACHE_DEFAULT_CONFIG_FILE_FULL_PATH='/etc/apache2/sites-available/default.conf'
APACHE_SHIBBOLETH_SP2_CONFIG_FILE_FULL_PATH='/etc/apache2/sites-available/shibboleth-sp2.conf'
SHIBBOLETH_XML_CONFIG_FILE_FULL_PATH='/etc/shibboleth/shibboleth2.xml'
# -- Constants End --

# Moving and Normalizing the default configuration path in the container
cp $DEFAULT_FILES_CONF_STATIC_PATH_INTO_CONTAINER/default.conf $APACHE_DEFAULT_CONFIG_FILE_FULL_PATH
sed -i s/$DEFAULT_NAME_TO_REPLACE_HOSTNAME/$EXTERNAL_CONF_HOSTNAME_SERVICE_PROVIDER/g $APACHE_DEFAULT_CONFIG_FILE_FULL_PATH

cp $DEFAULT_FILES_CONF_STATIC_PATH_INTO_CONTAINER/shibboleth-sp2.conf $APACHE_SHIBBOLETH_SP2_CONFIG_FILE_FULL_PATH
sed -i s/$DEFAULT_NAME_TO_REPLACE_HOSTNAME/$EXTERNAL_CONF_HOSTNAME_SERVICE_PROVIDER/g $APACHE_SHIBBOLETH_SP2_CONFIG_FILE_FULL_PATH
sed -i s/$DEFAULT_NAME_TO_REPLACE_ADDRESS_SHIBBOLETH_AUTH_APPLICATION/$EXTERNAL_CONF_SHIB_AUTH_APP_IP_PORT/g $APACHE_SHIBBOLETH_SP2_CONFIG_FILE_FULL_PATH

cp $DEFAULT_FILES_CONF_STATIC_PATH_INTO_CONTAINER/shibboleth2.xml $SHIBBOLETH_XML_CONFIG_FILE_FULL_PATH
sed -i s/$DEFAULT_NAME_TO_REPLACE_HOSTNAME/$EXTERNAL_CONF_HOSTNAME_SERVICE_PROVIDER/g $SHIBBOLETH_XML_CONFIG_FILE_FULL_PATH
sed -i s,$DEFAULT_NAME_TO_REPLACE_DISCOVERY_SERVICE,$EXTERNAL_CONF_DISCOVERY_SERVICE_URL,g $SHIBBOLETH_XML_CONFIG_FILE_FULL_PATH
sed -i s,$DEFAULT_NAME_TO_REPLACE_DISCOVERY_SERVICE_METADATA,$EXTERNAL_CONF_DISCOVERY_SERVICE_METADATA_URL,g $SHIBBOLETH_XML_CONFIG_FILE_FULL_PATH

cp $DEFAULT_FILES_CONF_DINAMIC_PATH_INTO_CONTAINER/$EXTERNAL_CONF_SERVICE_PROVIDER_CERTIFICATE_NAME /etc/ssl/certs/
cp $DEFAULT_FILES_CONF_DINAMIC_PATH_INTO_CONTAINER/$EXTERNAL_CONF_SERVICE_PROVIDER_KEY_NAME /etc/ssl/private/

a2ensite shibboleth-sp2.conf
a2ensite default.conf

mkdir -p .ssh/
AUTHORIZED_KEYS_PATH='/root/.ssh/authorized_keys'
touch $AUTHORIZED_KEYS_PATH
cat $DEFAULT_FILES_CONF_DINAMIC_PATH_INTO_CONTAINER/$EXTERNAL_CONF_SHIB_AUTH_VM_PUBLIC_KEY_NAME >> $AUTHORIZED_KEYS_PATH

service apache2 start
service apache2 reload
service shibd restart
